language: java

# move to the parent module before running the `mvn -T 1C test` command
before_script: cd talismane_parent

# build and run the tests
script: mvn -T 1C test

branches:
  only:
    - master
    - dev

jdk:
  - oraclejdk8
