//Copyright (C) 2014 Joliciel Informatique
package com.joliciel.talismane;

import java.util.List;
import java.util.Scanner;
import com.joliciel.talismane.lexicon.PosTaggerLexicon;
import com.joliciel.talismane.machineLearning.ClassificationModel;
import com.joliciel.talismane.machineLearning.MachineLearningModel;
import com.joliciel.talismane.parser.TransitionSystem;
import com.joliciel.talismane.posTagger.PosTag;
import com.joliciel.talismane.posTagger.PosTagSet;
import com.joliciel.talismane.posTagger.filters.PosTagSequenceFilter;
import com.joliciel.talismane.sentenceDetector.SentenceDetectorOutcome;
import com.joliciel.talismane.tokeniser.TokeniserOutcome;
import com.joliciel.talismane.tokeniser.filters.TokenSequenceFilter;

/**
 * An implementation of Talismane for a specific language.
 * @author Assaf Urieli
 *
 */
public interface LanguageSpecificImplementation {
	/**
	 * The default transition system for this language.
	 * @return
	 */
	public TransitionSystem getDefaultTransitionSystem();
	
	/**
	 * The default linguistic rules for this language.
	 * @return
	 */
	public LinguisticRules getDefaultLinguisticRules();

	/**
	 * Return a scanner containing the default text marker filter descriptors.
	 * @return
	 */
	public Scanner getDefaultTextMarkerFiltersScanner();

	/**
	 * Return a scanner containing the default token filter descriptors.
	 * @return
	 */
	public Scanner getDefaultTokenFiltersScanner();

	/**
	 * A list of filters to be applied to token sequences generated by the tokeniser
	 * prior to pos-tagging.
	 * @return
	 */
	public List<TokenSequenceFilter> getDefaultTokenSequenceFilters();

	/**
	 * A list of filters to be applied to pos-tag sequences generated by the pos-tagger
	 * after pos-tagging.
	 * @return
	 */
	public List<PosTagSequenceFilter> getDefaultPosTagSequenceFilters();
	
	/**
	 * Return the postag set for this language.
	 * @return
	 */
	public PosTagSet getDefaultPosTagSet();

	/**
	 * Return a scanner containing the default pos-tag set descriptors.
	 * @return
	 */
	public Scanner getDefaultPosTagSetScanner();
	
	/**
	 * Return a scanner containing the default pos tagger rule descriptors.
	 * @return
	 */
	public Scanner getDefaultPosTaggerRulesScanner();
	
	/**
	 * Return a scanner containing the default parser rule descriptors.
	 * @return
	 */
	public Scanner getDefaultParserRulesScanner();

	/**
	 * The default sentence model for this language.
	 * @return
	 */
	public ClassificationModel<SentenceDetectorOutcome> getDefaultSentenceModel();

	/**
	 * The default tokeniser model for this language.
	 * @return
	 */
	public ClassificationModel<TokeniserOutcome> getDefaultTokeniserModel();

	/**
	 * The default pos-tagger model for this language.
	 * @return
	 */
	public ClassificationModel<PosTag> getDefaultPosTaggerModel();

	/**
	 * The default parser model for this language.
	 * @return
	 */
	public MachineLearningModel getDefaultParserModel();
	
	/**
	 * Returns the default lexicon for this language.
	 * @return
	 */
	public PosTaggerLexicon getDefaultLexicon();
	
	/**
	 * Returns a list of TokenSequenceFilters available for this language.
	 * @return
	 */
	public List<Class<? extends TokenSequenceFilter>> getAvailableTokenSequenceFilters();
}